### ISSUE TITLE
Custom uid in case of transient NameID format

### ISSUE THREAD

**Issue by brukau** [omniauth/omniauth-saml#120] opened 2016-11-14 08:46 UTC
At the moment NameID is always used as uid
https://github.com/omniauth/omniauth-saml/blob/master/lib/omniauth/strategies/saml.rb#L139

But according to SAML spec in case of Transient Name Identifier (section 8.3.8, line 3359)
> identifier with transient semantics and SHOULD be treated
> as an opaque and temporary value by the relying party

Will it be possible to add an additional config option to use some attribute instead of NameID?
(Example in djangosaml2 https://github.com/knaperek/djangosaml2/blob/master/djangosaml2/backends.py#L92-L100)

**Comment by brukau** [comment] 2016-11-14 10:58
Related to https://github.com/omniauth/omniauth-saml/issues/106

**Comment by md5** [comment] 2016-11-15 19:40
@brukau I'm still happy to review a PR for this change, as I mentioned in #106.

Do you mind if we close this issue? I consider it a duplicate of #106.

**Comment by md5** [comment] 2016-11-15 19:41
On second thought, I guess it's not exactly a duplicate, but I'd like to see both issues addressed in a single PR.

**Comment by brukau** [comment] 2016-11-16 08:15
@md5 I would agree with your second comment

**Comment by md5** [comment] 2017-06-05 22:10
This should have been fixed by #121, though that PR has not yet made it into a release of `omniauth-saml`.

@supernova32 Do you have bandwidth to cut a new release in the near future?

**Closed by md5** 2017-06-05 22:10 UTC

**Comment by supernova32** [comment] 2017-06-05 23:05
@md5 I have some time tomorrow, I'll cut the release then.

**Comment by supernova32** [comment] 2017-06-07 16:14
@md5 I just pushed version 1.8.0 of omniauth-saml to GitHub and RubyGems

**Comment by md5** [comment] 2017-06-07 16:43
:+1:
